/**
 * Game definitions — metadata for all 10 distribution games.
 */

export const GAMES = [
  // Phase 1
  {
    id: '/normal',
    emoji: '⏱',
    title: '10秒チャレンジ',
    distribution: '正規分布',
    description: '目を瞑って10秒を数えてみよう。あなたの体内時計のズレが正規分布を作る！',
    color: 'normal',
    glow: 'normal',
    badge: 'Phase 1',
    phase: 1,
  },
  {
    id: '/exponential',
    emoji: '⚡',
    title: 'ランダム待ち受け',
    distribution: '指数分布',
    description: 'ランダムに光るシグナルを待とう。待ち時間が指数分布に従うことを体感！',
    color: 'exponential',
    glow: 'exponential',
    badge: 'Phase 1',
    phase: 1,
  },
  {
    id: '/poisson',
    emoji: '🎯',
    title: 'タップカウント',
    distribution: 'ポアソン分布',
    description: '10秒間に現れる星を捕まえよう！捕まえた数がポアソン分布になる。',
    color: 'poisson',
    glow: 'poisson',
    badge: 'Phase 1',
    phase: 1,
  },
  {
    id: '/uniform',
    emoji: '🎲',
    title: 'ルーレットストップ',
    distribution: '一様分布',
    description: '回転するルーレットを好きなところで止めよう。本当にランダムに止められる？',
    color: 'uniform',
    glow: 'uniform',
    badge: 'Phase 1',
    phase: 1,
  },
  // Phase 2
  {
    id: '/lognormal',
    emoji: '📏',
    title: '面積推定',
    distribution: '対数正規分布',
    description: '一瞬だけ表示される図形の面積を推定しよう。推定のズレが対数正規分布に。',
    color: 'lognormal',
    glow: 'lognormal',
    badge: 'Phase 2',
    phase: 2,
  },
  {
    id: '/geometric',
    emoji: '🎰',
    title: 'コイントス',
    distribution: '幾何分布',
    description: 'コインを投げ続けて表が出るまで何回かかる？幾何分布を体感しよう！',
    color: 'geometric',
    glow: 'geometric',
    badge: 'Phase 2',
    phase: 2,
  },
  {
    id: '/beta',
    emoji: '🏀',
    title: 'フリースロー',
    distribution: 'ベータ分布',
    description: 'シュートの成功率はどのくらい？ベイズ更新であなたの実力を推定！',
    color: 'beta',
    glow: 'beta',
    badge: 'Phase 2',
    phase: 2,
  },
  // Phase 3
  {
    id: '/cauchy',
    emoji: '🎯',
    title: 'レーザーポインター',
    distribution: 'コーシー分布',
    description: 'ランダムな角度でレーザーを照射。着弾点の極端なばらつきを体感！',
    color: 'cauchy',
    glow: 'cauchy',
    badge: 'Phase 3',
    phase: 3,
  },
  {
    id: '/weibull',
    emoji: '💡',
    title: '電球寿命',
    distribution: 'ワイブル分布',
    description: '10個の電球がいつ切れるか予測しよう。故障率の変化を体感！',
    color: 'weibull',
    glow: 'weibull',
    badge: 'Phase 3',
    phase: 3,
  },
  {
    id: '/gamma',
    emoji: '☕',
    title: '注文待ち',
    distribution: 'ガンマ分布',
    description: 'カフェで3人分の注文を待つ時間は？指数分布の和がガンマ分布に！',
    color: 'gamma',
    glow: 'gamma',
    badge: 'Phase 3',
    phase: 3,
  },
];
