/**
 * Game definitions — metadata for all 10 distribution games.
 */

export const GAMES = [
  // Phase 1
  {
    id: '/normal',
    emoji: '⏱',
    title: '10秒チャレンジ',
    distribution: '正規分布',
    description: '体内時計で10秒を計測する. 計測誤差の分布が正規分布に従うことを確認する.',
    color: 'normal',
    glow: 'normal',
    badge: 'Phase 1',
    phase: 1,
  },
  {
    id: '/exponential',
    emoji: '⚡',
    title: 'ランダム待ち受け',
    distribution: '指数分布',
    description: 'ポアソン過程に従うシグナルの待ち時間を記録する. メモリレス性を観察する.',
    color: 'exponential',
    glow: 'exponential',
    badge: 'Phase 1',
    phase: 1,
  },
  {
    id: '/poisson',
    emoji: '🎯',
    title: 'タップカウント',
    distribution: 'ポアソン分布',
    description: '一定時間内に発生するイベントの回数を数える. カウントデータの分布を観察する.',
    color: 'poisson',
    glow: 'poisson',
    badge: 'Phase 1',
    phase: 1,
  },
  {
    id: '/uniform',
    emoji: '🎲',
    title: 'ルーレットストップ',
    distribution: '一様分布',
    description: 'ルーレットの停止位置が一様分布に従うか検証する. 人間のバイアスを可視化する.',
    color: 'uniform',
    glow: 'uniform',
    badge: 'Phase 1',
    phase: 1,
  },
  // Phase 2
  {
    id: '/lognormal',
    emoji: '📏',
    title: '面積推定',
    distribution: '対数正規分布',
    description: '図形の面積を推定し,推定値と真値の比を記録する. 比率の分布が対数正規分布に従うことを確認する.',
    color: 'lognormal',
    glow: 'lognormal',
    badge: 'Phase 2',
    phase: 2,
  },
  {
    id: '/geometric',
    emoji: '🎰',
    title: 'コイントス',
    distribution: '幾何分布',
    description: 'Bernoulli試行を繰り返し,初めて成功するまでの試行回数を記録する.',
    color: 'geometric',
    glow: 'geometric',
    badge: 'Phase 2',
    phase: 2,
  },
  {
    id: '/beta',
    emoji: '🏀',
    title: 'フリースロー',
    distribution: 'ベータ分布',
    description: '成功/失敗の二値データから,成功確率の事後分布をベイズ推定する.',
    color: 'beta',
    glow: 'beta',
    badge: 'Phase 2',
    phase: 2,
  },
  // Phase 3
  {
    id: '/cauchy',
    emoji: '🎯',
    title: 'レーザーポインター',
    distribution: 'コーシー分布',
    description: 'ランダムな角度で壁にレーザーを照射し,着弾位置の分布を観察する. 裾の重さを体感する.',
    color: 'cauchy',
    glow: 'cauchy',
    badge: 'Phase 3',
    phase: 3,
  },
  {
    id: '/weibull',
    emoji: '💡',
    title: '電球寿命',
    distribution: 'ワイブル分布',
    description: '形状パラメータ $k > 1$ の場合の故障率増加を,電球の寿命シミュレーションで観察する.',
    color: 'weibull',
    glow: 'weibull',
    badge: 'Phase 3',
    phase: 3,
  },
  {
    id: '/gamma',
    emoji: '☕',
    title: '注文待ち',
    distribution: 'ガンマ分布',
    description: '独立な指数分布に従う待ち時間の和がガンマ分布に従うことを,シミュレーションで確認する.',
    color: 'gamma',
    glow: 'gamma',
    badge: 'Phase 3',
    phase: 3,
  },
  // Phase 4
  {
    id: '/infogeo',
    emoji: '📐',
    title: '統計多様体と測地線',
    distribution: '情報幾何学',
    description: 'Fisher情報計量による分布空間の歪みを可視化する. パラメータ空間上の測地線が分布をどう変えるか観察する.',
    color: 'normal',
    glow: 'normal',
    badge: 'Phase 4',
    phase: 4,
  },
];
